In [108]:
import pandas as pd
import numpy as np

In [109]:
df1=pd.read_csv("train.csv")
df1.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [110]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [111]:
dfle=df1
cols=['LotFrontage','MSZoning','Street','Alley','LotShape','LandContour','Utilities','LotConfig','Neighborhood','LandSlope','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition']
for col in cols:
    dfle[col]=le.fit_transform(dfle[col])
    dfle

In [112]:
dfle['LotFrontage']=dfle['LotFrontage'].fillna(dfle['LotFrontage'].median())

In [113]:
dfle['GarageYrBlt']=dfle['GarageYrBlt'].fillna(dfle['GarageYrBlt'].median())

In [114]:
dfle['MasVnrArea']=dfle['MasVnrArea'].fillna(dfle['MasVnrArea'].median())

In [115]:
X=dfle.drop(['SalePrice','Id'],axis='columns')
X

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,3,36,8450,1,2,3,3,0,4,...,0,0,3,4,4,0,2,2008,8,4
1,20,3,51,9600,1,2,3,3,0,2,...,0,0,3,4,4,0,5,2007,8,4
2,60,3,39,11250,1,2,0,3,0,4,...,0,0,3,4,4,0,9,2008,8,4
3,70,3,31,9550,1,2,0,3,0,0,...,0,0,3,4,4,0,2,2006,8,0
4,60,3,55,14260,1,2,0,3,0,2,...,0,0,3,4,4,0,12,2008,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,3,33,7917,1,2,3,3,0,4,...,0,0,3,4,4,0,8,2007,8,4
1456,20,3,56,13175,1,2,3,3,0,4,...,0,0,3,2,4,0,2,2010,8,4
1457,70,3,37,9042,1,2,3,3,0,4,...,0,0,3,0,2,2500,5,2010,8,4
1458,20,3,39,9717,1,2,3,3,0,4,...,0,0,3,4,4,0,4,2010,8,4
1459,20,3,46,9937,1,2,3,3,0,4,...,0,0,3,4,4,0,6,2008,8,4

In [116]:
y=dfle.SalePrice
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [117]:
from sklearn.model_selection import train_test_split

In [118]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [119]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [120]:
model.fit(X_train,y_train)

LinearRegression()

In [121]:
dfle.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [122]:
null_counts=dfle.isnull().sum()
print(null_counts[null_counts>0])

Series([], dtype: int64)

In [123]:
model.predict(X_test)

array([168675.80173091, 123925.14200098, 151318.70455312, 143693.46553219,
        70214.50145932, 306378.86467632, 163065.67744109, 144798.99375882,
       213671.70652388, 220377.24668076, 160837.19111572, 116835.80591202,
       169331.88473827, 125016.5208034 , 174390.53594561,  92534.57191075,
       132125.90095128, 169695.39485449, 316748.39559656, 125429.72257575,
       129177.91078788, 163591.3603979 , 403730.671708  , 140268.01293979,
       399935.45067242, 174323.38397099, 316388.58336359, 256513.45553175,
        72902.07020987, 218074.07501317, 264714.47870453, 180273.7917184 ,
       147451.23314353, 163599.92571691, 229590.59990924, 126891.28831407,
       263825.49002278, 110657.35758892, 131540.15219611, 219431.9262542 ,
       111692.63361336, 137289.73016244, 232050.74227959, 247779.15934816,
        88885.96320485, 142484.51994996, 150884.71038596, 136824.91311412,
       105716.37672802, 230396.98430991, 296673.81915293, 158767.51275506,
       282173.07277695, 261666.24653276, 152881.83681388, 118133.31170375,
        62104.49066842, 148831.41036441, 108762.6800337 , 203186.35487358,
       167972.64506902, 108812.49375111, 178339.411354  , 176193.32511612,
       173189.07731557, 216559.42316974, 239933.22031957, 134572.9990718 ,
       234201.71296646, 132010.82758289, 109768.27073464,  38315.14303683,
       142422.1154356 , 125807.17146003, 157273.18770963, 119887.03746654,
       409407.73623222, 187466.28762004, 228040.82691254, 283073.41745762,
       152478.08977247, 247965.09103938, 137651.61997086, 107995.00522307,
       159351.08550927, 201154.22319382,  60588.94814138, 280509.13736283,
       108650.67711123, 177672.36751279,  68937.58929081, 106954.36160611,
       211016.1877275 , 173446.05817058, 158277.75510796, 312101.4237628 ,
       192095.19589679,  92032.31724771, 122789.24261123, 209967.13057155,
       220255.10756887, 261956.6141067 , 225638.51278494, 294834.63176938,
       119267.16353888, 560696.0128943 , 185659.60597609, 145759.64638192,
       201659.65122223,  85753.09536965, 226928.54572832, 206584.51001217,
       256494.64137896, 216272.82001019, 180582.1766428 , 159539.69291729,
       197170.70409518, 143942.53030897, 192288.08939042, 122730.89064137,
       193738.79407972,  84449.47052001, 250488.23831282, 124744.40121578,
       181833.25384973,  98095.26305471,  83000.58636887, 120195.69849237,
       233454.52352693, 217126.87483101, 216956.53628683, 158408.76342222,
       313579.57620471, 139546.63595253, 120887.71478834, 191139.66817045,
       245314.58263198, 249554.21396807, 151056.76284269, 113445.24286342,
       130737.93626021, 201244.16323223, 133587.02336159, 392330.58029993,
       189216.51931012, 182928.49406161, 131837.3487309 ,  98747.28814562,
       277811.84714768, 125269.168837  , 216845.98551362,  69028.5087252 ,
       315357.72557303, 131981.21418752, 111698.65901531, 166628.39371748,
       146474.98859556, 218203.51524146, 131570.27022007,  84769.05213827,
       330236.63120991, 286137.79184438, 257636.96163015, 187966.69175531,
       141968.47295679, 141145.72998641, 233677.97515274,  85743.32612414,
       133832.70738997, 135229.46364727, 128437.40714629,  95183.72086254,
       306009.14873872, 119061.79813684, 138944.01047646,  95740.21159012,
       314087.14921369, 186283.27532467, 258544.99631933, 126215.43611498,
        52671.56095181, 370169.02826839,  51999.64645282, 126465.94543277,
       134258.89795191, 100691.33295826, 137282.88836446, 113437.5801143 ,
       203299.79335015, 164616.13412641,  95053.85081069, 181039.00637334,
       131577.12342046, 352948.40929189, 174823.82113195, 200011.35185057,
        41525.4092645 , 277320.89193108, 154196.8532139 , 130835.00761627,
       271479.24052597, 145029.27570958,  91475.54576646, 262163.72058785,
       341816.49403745,  89888.67452563, 228198.67372093,  60981.19280179,
       230358.50933381, 215185.78089601, 101419.90518898,  74820.1578166 ,
        75601.26370085, 115554.42198561, 104263.80643483, 142248.04822274,
       351132.80188663, 264910.904592  , 192285.03707847, 210319.70762218,
       312430.31948951,  87233.65981207, 142712.97278886, 213914.13502932,
       211440.99201011, 121299.18246497, 181953.84845995, 225111.43009934,
       160425.27947926, 132669.12393183, 163671.85998854, 110612.63672124,
       128009.96185779, 176360.57970935, 139371.86577368, 295775.29238155,
       105959.39014576, 193296.16134064, 132628.32095758, 157973.27752583,
       143703.19749387, 166377.2048    , 238862.42626732, 297131.90874989,
       113501.48027624, 200962.04022289, 233511.73509181, 301337.29971696,
       312186.18599606, 316772.87459867, 304279.44311919, 188409.41375388,
        92195.44576394, 183221.02255496,  84434.60451979, 212967.40282884,
       199917.2233743 , 250467.94192697, 106399.13713194, 153299.36953418,
       169853.85525872, 173932.33932288, 193367.79170269, 121953.5355238 ,
        97924.90796097, 208289.28368768, 170387.87844845, 242273.23336194,
       270575.10026858, 190681.5210206 , 224920.62910298, 231882.83424965,
       172119.05698881, 200253.09294185, 180876.34572652,  72969.12891808,
       416347.59837679, 142807.6403781 , 123046.20480962, 247543.50813211,
       272396.72258079, 127925.22643002, 327615.08895683, 192043.7751816 ,
       199267.52646654, 109382.6721278 , 169036.08180491, 131589.77208076,
       308706.47646953, 147881.72552463, 128044.383613  , 161398.16157437])

In [124]:
model.score(X_test,y_test)

0.763004889696616

In [125]:
df2=pd.read_csv("test.csv")
df2.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [126]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [127]:
dfle2=df2
cols=['LotFrontage','MSZoning','Street','Alley','LotShape','LandContour','Utilities','LotConfig','Neighborhood','LandSlope','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition']
for col in cols:
    dfle2[col]=le.fit_transform(dfle2[col])
    dfle2

In [128]:
dfle2['LotFrontage']=dfle['LotFrontage'].fillna(dfle2['LotFrontage'].median())

In [129]:
dfle2['GarageYrBlt']=dfle['GarageYrBlt'].fillna(dfle2['GarageYrBlt'].median())

In [130]:
dfle2['MasVnrArea']=dfle['MasVnrArea'].fillna(dfle2['MasVnrArea'].median())

In [131]:
dfle2

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,2,36,11622,1,2,3,3,0,...,120,0,2,2,3,0,6,2010,8,4
1,1462,20,3,51,14267,1,2,0,3,0,...,0,0,2,4,0,12500,6,2010,8,4
2,1463,60,3,39,13830,1,2,0,3,0,...,0,0,2,2,3,0,3,2010,8,4
3,1464,60,3,31,9978,1,2,0,3,0,...,0,0,2,4,3,0,6,2010,8,4
4,1465,120,3,55,5005,1,2,0,1,0,...,144,0,2,4,3,0,1,2010,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,4,33,1936,1,2,3,3,0,...,0,0,2,4,3,0,6,2006,8,4
1455,2916,160,4,33,1894,1,2,3,3,0,...,0,0,2,4,3,0,4,2006,8,0
1456,2917,20,3,56,20000,1,2,3,3,0,...,0,0,2,4,3,0,9,2006,8,0
1457,2918,85,3,37,10441,1,2,3,3,0,...,0,0,2,2,2,700,7,2006,8,4
1458,2919,60,3,39,9627,1,2,3,3,0,...,0,0,2,4,3,0,11,2006,8,4

In [132]:
model.predict(X)

array([213387.88935949, 196847.42894042, 217366.72847177, ...,
       252769.2704531 , 151868.81441058, 166628.39371748], shape=(1460,))

In [133]:
model.score(X,y)

0.843270004113537

In [135]:
import pandas as pd
Test_data=pd.read_csv('test.csv') 
X_test=Test_data.drop(columns=['Id'])

# Make predictions
predictions = model.predict(X_test)

# Create DataFrame
submission = pd.DataFrame({
    'SalePrice': predictions,
  'Id': Test_data['Id'],
})

# Save to CSV
submission.to_csv('submission.csv', index=False)

ValueError: Input contains NaN